user:
  name: 255
  email: 255
  password: 6
  phone: 255
  address: 255
  size: 50
  gravatar_size: 80
  per_page: 5
author:
  name: 255
  password: 6
  email: 255
  profile: 255
publisher:
  name: 255
category:
  name: 255
book:
  name: 255
  author: 255
  category: 255
  content: 255
  publisher: 255
  pages: 11
  quantity: 11
  per_page: 12
request_detail:
  quantity: 11
comment:
  content: 255
static_page:
  per_page: 6
