user:
  name: 255
  email: 255
  password: 6
  phone: 255
  address: 255
  size: 50
  gravatar_size: 80
  per_page: 5
author:
  name: 255
  password: 6
  email: 255
  profile: 255
publisher:
  name: 255
category:
  name: 255
  per_page: 6
book:
  name: 255
  author: 255
  category: 255
  content: 255
  publisher: 255
  pages: 11
  quantity: 11
  per_page: 12
request:
  per_page: 10
request_detail:
  quantity: 11
comment:
  content: 255
static_page:
  per_page: 12
  page: 6
mail_default: "nguyenvanbinh3479@gmail.com"
address: "smtp.gmail.com"
port: 587
domain: "localhost:3000"
authentication: "plain"
